server:
  port: 8082

spring:
  boot:
    admin:
      client:
        url: http://localhost:9090
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: email # Different Consumer should have different group id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

kafka:
  topic:
    json:
      email:
        name: order-email-topic

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: Email Service Kafka Consumer
    environment: ${spring.profiles.active}
    version: '@project.version@'